.PHONY: clean All

All:
	@echo "----------Building project:[ fairgroundRide - Debug ]----------"
	@cd "fairgroundRide" && "$(MAKE)" -f  "fairgroundRide.mk"
clean:
	@echo "----------Cleaning project:[ fairgroundRide - Debug ]----------"
	@cd "fairgroundRide" && "$(MAKE)" -f  "fairgroundRide.mk" clean
