.PHONY: clean All

All:
	@echo "----------Building project:[ UOCThemePark - Release ]----------"
	@"$(MAKE)" -f  "UOCThemePark.mk"
clean:
	@echo "----------Cleaning project:[ UOCThemePark - Release ]----------"
	@"$(MAKE)" -f  "UOCThemePark.mk" clean
